name: ci

on:
  push:
    branches: main

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest,  ubuntu-latest ]
        toolchain: [nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}
            override: true
      - name: Install gnu toolchain on windows
        if: matrix.os == 'windows-latest'
        run: |
          rustup toolchain install stable-x86_64-pc-windows-gnu
          rustup target add x86_64-pc-windows-gnu
          rustup set default-host x86_64-pc-windows-gnu
      - name: Build
        run: cargo build --locked --release --all-targets
